version: '3.3'
services:
  compose_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hhnatiuk/lab4:cmp-app
    container_name: compose-app
    networks:
      - public
    ports:
      - 8000:8000
  compose_mon:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: hhnatiuk/lab4:cmp-mon
    container_name: compose-mon
    depends_on: 
      - compose_app
    networks:
      - public

networks:
  public:
    driver: bridge
